name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

# Add permissions block at the workflow level
permissions:
  contents: write # Required for creating releases
  packages: write # Required for publishing to crates.io

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: junkanoo-linux-x86_64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            artifact_name: junkanoo-linux-aarch64
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            artifact_name: junkanoo-windows
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            artifact_name: junkanoo-macos-x86_64
            target: x86_64-apple-darwin
          - os: macos-latest
            artifact_name: junkanoo-macos-aarch64
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Install cross-compilation tools
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Publish to crates.io
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.target }}/release/junkanoo*
          if-no-files-found: error

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Package macOS artifacts
        run: |
          cd artifacts/junkanoo-macos-x86_64
          tar -czf junkanoo-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz junkanoo
          rm junkanoo
          cd ../junkanoo-macos-aarch64
          tar -czf junkanoo-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz junkanoo
          rm junkanoo

      - name: Package Linux artifacts
        run: |
          cd artifacts/junkanoo-linux-x86_64
          tar -czf junkanoo-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz junkanoo
          rm junkanoo
          cd ../junkanoo-linux-aarch64
          tar -czf junkanoo-${{ github.ref_name }}-aarch64-unknown-linux-gnu.tar.gz junkanoo
          rm junkanoo

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/junkanoo-linux-x86_64/*
            artifacts/junkanoo-linux-aarch64/*
            artifacts/junkanoo-windows/*
            artifacts/junkanoo-macos-x86_64/*
            artifacts/junkanoo-macos-aarch64/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
